### ISSUE TITLE
Receiving errors when attempting to use key files

### ISSUE THREAD

**Issue by timmyb824** [alajmo/sake#10]
**Is your feature request related to a problem? Please describe.**
I wasn't sure if this was the same problem as #5 so I'm opening a new issue just in case. I'm using a mac and whenever I try to run even a basic command like `sake run ping --all` using an identity key file I get one of two errors:

1) error: failed to parse `/Users/timothybryant/.ssh/id_ed25519_personal`
  ssh: key is not password protected

so I created a new key file with a passphrase and now I get:

2.  error: failed to parse `/Users/timothybryant/.ssh/id_rsa_password_protected`
  bcrypt_pbkdf: empty password

I also tried using the `-i` command line argument instead but got the same results.

**Describe the solution you'd like**
I'm trying to run remote commands on VM's I have and I had hoped sake would be able to do that by ssh'ing to the hosts using the key files I have stored. 

**Additional context**
Most of what I've done thus far (e.g. tasks, specs, etc) has come from the repo examples. Here is an example config for one of my VM's though:

```
servers:
  localhost:
    desc: localhost
    host: localhost
    local: true
    #work_dir: /tmp
    tags: [local]
  vm303:
    host: 192.168.1.74
    user: jsmith
    port: 22
    identity_file: ~/.ssh/id_ed25519_personal
    local: false
    tags: [cluster]
```
