### ISSUE TITLE
Be aware of `~/.ssh/config`

### ISSUE THREAD

**Issue by DannyBen** [alajmo/sake#12]
I was trying to configure a server in sake.yaml, by simply using the hostname as it is written in my `~/.ssh/config`, but realized this does not work.

### Example `sake.yaml`:

```yaml
servers:
  myserver:
    host: myserver
```

### Example `~/.ssh/config`:

```
Host myserver
  Hostname 123.123.123.123
  User root
```

Can this be made to work?
