### ISSUE TITLE
Should fail on non-zero exit

### ISSUE THREAD

**Issue by aldy505** [alajmo/sake#23]
## Is your feature request related to a problem? Please describe

Currently sake does not exit with non-zero code (or, simply, fail) when the command we're executing exited with non-zero code. 

It'd be nice if it would fail on non-zero code.  

## Describe the solution you'd like

I think the feature should be optional to remain backward compatible with existing users. So, to have sake fail on non-zero exit code, the user should incite another CLI options like `--fail`. 

## Additional context

The sake command that I use to produce this issue was `sake run <command> --servers <server> --known-host-file <file>`

Let me know if I was wrong about the exit behavior or any needed reproductions.

**Comment by aldy505** [comment]
I can't find the exact issue as I was searching on the CD pipeline, maybe I executed it from my local machine. As I remembered it, it's just a normal `npm install` (Nodejs stuff) that got a timeout error, and I also remembered that I put the `--any-errors-fatal` flag.

But I will surely create a repro over the weekend if that's okay.

**Comment by aldy505** [comment]
Sorry it took a while. I ran it on the CD server with the sake configuration as:

```yaml
pull_master:
    desc: Pull from the master branch
    cmd: |
      git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/some-organization/some-repository.git
      git pull
      git remote set-url origin https://github.com/some-organization/some-repository.git
    work_dir: /home/user/some-repository
    env:
      GIT_USERNAME: $(echo $GIT_USERNAME)
      GIT_PASSWORD: $(echo $GIT_PASSWORD)
      DEBIAN_FRONTEND: noninteractive
```

The CD results is (the first line is the command I executed):

```
Run yes | sake run pull_master --servers onpremise -i /root/.ssh/id_ed25519 --known-hosts-file /root/.ssh/known_hosts --any-errors-fatal
Unknown Host: ***:22 
Fingerprint: <redacted>
Would you like to add it? type (y)es or (n)o: 
TASK [pull_master: Pull from the master branch] 
*** | error: No such remote 'origin'
*** | There is no tracking information for the current branch.
*** | Please specify which branch you want to merge with.
*** | See git-pull(1) for details.
*** | 
*** |     git pull <remote> <branch>
*** | 
*** | If you wish to set tracking information for this branch you can do so with:
*** | 
*** |     git branch --set-upstream-to=<remote>/<branch> master
*** | 
*** | Process exited with status 2
*** | error: No such remote 'origin'
```
