### ISSUE TITLE
Allow for full range of SSH port numbers

### ISSUE THREAD

**Issue by AshishShenoy** [alajmo/sake#3]
Currently only SSH port numbers up to 255 are supported. But many servers are configured by disabling connections on the default SSH port (22) and using a non well known port (such as 2200) instead. 

This is because port is currently defined as a `uint8`. A change in data type to `uint16` should fix this and allow for the full range of port numbers to be used.

This is the error message received when using a large port number:
![image](https://user-images.githubusercontent.com/45451652/173236899-dd931030-e8ba-40b9-9ddf-cfa4e4622f80.png)

Config file:
```yaml
servers:
  server:
    host: 192.168.1.7
    port: 2222
  
tasks:
  ping:
    desc: Pong
    cmd: echo "pong"
```
