### ISSUE TITLE
error: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by retiolum** [alajmo/sake#33]
- [x] I have the latest version of sake
- [x] I have searched through the existing issues

## Info

- OS
  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows
  - [ ] other

- Shell
  - [x] Bash
  - [ ] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

- Version: 0.10.3

## Problem / Steps to reproduce

I get the following error message when running a command, no matter if I target a single server or all my servers:
`error: strconv.ParseInt: parsing "": invalid syntax`

`sake check` says that my configuration is OK.

This is my definition file:
```
servers:
    production:
        host: my.server.de
        port: 123
        user: user1
        local: false
        tags:
            - remote
    stage:
        host: my.server.de
        port: 123
        user: user2
        local: false
        tags:
            - remote
    test:
        host: my.server.de
        port: 123
        user: user3
        local: false
        tags:
            - remote
    internal:
        host: 192.1.2.3
        user: user
        local: false
        tags:
            - internal

tasks:
    ping:
        desc: Ping server
        cmd: ping $SAKE_SERVER_HOST
        local: true
    pwd:
        desc: Print working directory
        cmd: pwd
```

And this is what I'm running:
`sake run ping --all`
