### ISSUE TITLE
Identity file not used when using `sake ssh`

### ISSUE THREAD

**Issue by zasdaym** [alajmo/sake#63]
- [x] I have the latest version of sake
- [x] I have searched through the existing issues

## Info

- OS
  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows
  - [ ] other

- Version: 0.15.1

- Authentication:
  - [ ] Identity Key + Passphrase
  - [x] Identity Key
  - [ ] Passphrase
  - [ ] SSH Agent

- Key Type:
  - [x] rsa
  - [ ] ed25519
  - [ ] other

- Key Format:
  - [ ] rfc4716
  - [ ] pkcs8
  - [x] pem

## Problem / Steps to reproduce

When using `identity_file` on `sake.yaml`, `sake ssh` won't use the identity file.

```
disable_verify_host: true

servers:
  srv1:
    host: x.x.x.x
    user: root
    identity_file: private.pem
```

`sake ssh srv1`
