### ISSUE TITLE
Issues with SSH when using 1Password SSH agent

### ISSUE THREAD

**Issue by kquinsland** [alajmo/sake#64]
- [X] I have the latest version of sake
- [X] I have searched through the existing issues

## Info

- OS
  - [ ] Linux
  - [X] Mac OS X
  - [ ] Windows
  - [ ] other

- Shell
  - [ ] Bash
  - [X] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

-----

Given this yaml:

```yaml
# ❯ /bin/cat sake.yaml
# See: https://github.com/alajmo/sake/blob/main/docs/config-reference.md
servers:
    test:
        desc: try sake tool on test server
        host: test.zone.corp
        local: false
        work_dir: /home/karl.quinsland
        tags:
            - zone.corp

tasks:
    docker_container_list:
        desc: Lists all docker containers
        cmd: docker container list --all
```

And this command:

```shell
❯ sake --verbose --config=./sake.yaml run docker_container_list --tags=zone.corp
error: dial unix ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock: connect: no such file or directory
```

But that is most certainly a file:

```shell
❯ ls -lah ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
Alias tip: lsa ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
srw------- 1 karl.quinsland staff 0 Mar 19 09:19 '/Users/karl.quinsland/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock'=
```

```shell
❯ sake --version
Version: 0.15.1
Commit: 72850d1
Date: 2023-09-25T09:55:59Z
```
